### ISSUE TITLE
onnx model

### ISSUE THREAD

**Issue by carter54** [bychen7/Face-Restoration-TensorRT#1]
Hi @bychen7 ~ thx for sharing this work. Could you share the way of converting GPEN torch model to onnx model please?

**Comment by bychen7** [comment]
Hi @carter54 I have uploaded the implementation of ModulatedConv2d. You can directly replace the ModulatedConv2d in GPEN with it and then export the onnx model.
https://github.com/bychen7/Face-Restoration-TensorRT/blob/58230da6a8adb87ec819c695e2e9a68344dbbe65/misc/ModulatedConv2d.py#L1

**Comment by carter54** [comment]
Thx for the reply~ I used the following code to generate GPEN onnx model from torch model
```
torch.onnx.export(torch_model, dummy_input.to(device), onnx_file_name,
                  input_names=input_names,
                  output_names=output_names,
                  verbose=False,
                  opset_version=10,
                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
```
and used following code to generate trt engine from onnx model
```
trtexec --onnx=GPEN-BFR-256.onnx --saveEngine=GPEN-BFR-256.trt
```

But I can only achieve 11.5ms/frame with T4 GPU and tensorRT python API.

Did you apply other tricks to achieve 5.5ms/frame? :) 👍

**Comment by bychen7** [comment]
I tested it on RTX3090, which has better performance than T4. You can refer to this https://askgeek.io/en/gpus/vs/NVIDIA_GeForce-RTX-3090-vs-NVIDIA_Tesla-T4. Also, I warmed up the model ten times before running the test one hundred times and taking the average speed.

**Comment by carter54** [comment]
I c, thx~

**Comment by zimenglan-sysu-512** [comment]
hi @bychen7 
the floating point is fp16 or fp32?

**Comment by bychen7** [comment]
Hi,@zimenglan-sysu-512 It is fp32.
