### ISSUE TITLE
encountering error while loading shared libraries: libnvinfer_plugin.so.8 when convert onnx model

### ISSUE THREAD

**Issue by nelsontseng0704** [bychen7/Face-Restoration-TensorRT#10]
Hi. Thanks for the great work. I am using a ubuntu machine with GPU and following your tutorial from step 1 to step 4. However, I encounter some problem when I am trying to run 
`./convert ../models/model.onnx -s ../models/model.engine`
and return
`error while loading shared libraries: libcublas.so.12: cannot open shared object file: No such file or directory`

How do I solve this problem? Welcome to any advice. 
Thank you

**Comment by bychen7** [comment]
Hi, @nelsontseng0704 I think you can perform a check from the following two aspects:
1. Ensure that the CUDA version matches the TensorRT version.
2. Verify if the environment variables have been added.

My testing environment is Ubuntu 20.04 with CUDA 11.7 & TensorRT-8.2.4.2/TensorRT-8.6.1.6 on an RTX 3090. You can refer to this for guidance.

**Comment by bychen7** [comment]
Close for now. Feel free to reopen if you have any questions.
