### ISSUE TITLE
Which model has better quality for Teeth and mouth regions?

### ISSUE THREAD

**Issue by nelsontseng0704** [bychen7/Face-Restoration-TensorRT#11]
I utilized the model weights provided by the repository. During the process of facial restoration and video generation, I observed noticeable pixelation effects on the teeth. My first question is about whether the model in the repository is GPEN or GFPGAN. 
Second, to achieve an enhanced quality in facial restoration, particularly for teeth and mouth regions, which model would you recommend?

Thanks in advance.

**Comment by bychen7** [comment]
Hi, @nelsontseng0704 The provided model is GPEN, and I'm not quite understanding the "pixelation effects." Are there any visual examples available?

**Comment by bychen7** [comment]
Close for now. Feel free to reopen if you have any questions.
