### ISSUE TITLE
Cuda failure: 700

### ISSUE THREAD

**Issue by lschaupp** [bychen7/Face-Restoration-TensorRT#12]
I am getting a 700 error with the model-512.onnx model.
However the model.onnx works without any issue.

Anyone knows why or can reproduce this?

**Comment by bychen7** [comment]
Hi, @lschaupp Can you provide more details about the error? If you are using `model-512.onnx`, you need to change the following two lines to 512.
https://github.com/bychen7/Face-Restoration-TensorRT/blob/298f55e856c1cf42ad6b4523c33dc1cfedbca5d3/face_restoration.hpp#L21-L22

**Comment by lschaupp** [comment]
Perfect. Can be closed now.
