### ISSUE TITLE
Directly convert GFPGAN1.4.onnx into GFPGAN1.4.engine and then receive API usage error when run images

### ISSUE THREAD

**Issue by nelsontseng0704** [bychen7/Face-Restoration-TensorRT#13]
I convert GFPGAN1.4.onnx by running ./convert ../models/model.onnx -s ../models/model.engine
When I run ./demo ../models/model.engine -i ../images/test.png

I receive error like:

`Loaded engine size: 372 MiB
[MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +368, now: CPU 0, GPU 368 (MiB)
[MS] Running engine with multi stream info
[MS] Number of aux streams is 7
[MS] Number of total worker streams is 8
[MS] The main stream provided by execute/enqueue calls is the first worker stream
[MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +437, now: CPU 0, GPU 805 (MiB)
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
3: Cannot find binding of given name: output
3: [engine.cpp::getUserRegion::1312] Error Code 3: Internal Error (call of getBindingDataType with invalid bindingIndex -1)
3: [executionContext.cpp::enqueueInternal::795] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::795, condition: bindings[x] || nullBindingOK
)
Cuda failure: 1
Aborted (core dumped)`

I also change from 256 to 512:
https://github.com/bychen7/Face-Restoration-TensorRT/blob/298f55e856c1cf42ad6b4523c33dc1cfedbca5d3/face_restoration.hpp#L21-L22

Any suggestion if I want to run this with GFPGAN 1.4.
Thanks in advance.

**Comment by bychen7** [comment]
Hi, @nelsontseng0704 This repository hasn't been tested with GFPGAN, it mainly focuses on GPEN. Sorry, I don't have any particular suggestions right now.

**Comment by bychen7** [comment]
Close for now. Feel free to reopen if you have any questions.
