### ISSUE TITLE
inference is too..........oo slow

### ISSUE THREAD

**Issue by Liuqh12** [bychen7/Face-Restoration-TensorRT#19]
My speed about: 40ms/frame
Environment:
OS: win11
device: laptop RTX4070
driver:537.13
CUDA:12.2
TensorRT:8.6.1
onnx file from:: https://github.com/harisreedhar/Face-Upscalers-ONNX/releases/tag/Models
Even if your project under window also: 40+ms/Frame.
any idea? thank you.

**Comment by fanghaiquan1** [comment]
请问这个时间问题有办法吗？我目前也是需要0.05s一张图

**Comment by fanghaiquan1** [comment]
用不用tensorrt 区别不大，请问如何提速？

**Comment by Liuqh12** [comment]
实测，pytorch2.1.2+cu118，10ms/frame。
