### ISSUE TITLE
is it possible to support 512x512

### ISSUE THREAD

**Issue by huangxin168** [bychen7/Face-Restoration-TensorRT#2]
Great job!
the speed is much faster than pytorch origin model.
it seams the input/output size is 256x256, 
is it possible to support 512x512 as the gfpgan officical release model?

**Comment by bychen7** [comment]
Hi, @huangxin168 , I have updated the GPEN 512 model ([BaiduPan](https://pan.baidu.com/s/19klcec1LlkWn_JspH82VPg) pwd: yxt7), which has similar results to GFPGAN. With TensorRT-8.2.4.2 and 3090, the speed is about 30ms. You need to change the following two lines to 512.
https://github.com/bychen7/Face-Restoration-TensorRT/blob/58230da6a8adb87ec819c695e2e9a68344dbbe65/face_restoration.hpp#L21-L22

**Comment by huangxin168** [comment]
Thanks for your quick response!
I test it on a 4090 got 90fps more than 2times to the pytorch version.

**Comment by bychen7** [comment]
close for now.

**Comment by Fibonacci134** [comment]
> close for now.

Please provide a Googledrive link if possible. Thank you.
