### ISSUE TITLE
when you support GFPGANv1.3?

### ISSUE THREAD

**Issue by SeanLiu081** [bychen7/Face-Restoration-TensorRT#4]
The onnx you provided is gpen，When can we provide GFPGAN？

**Comment by bychen7** [comment]
I have no plans to release it at the moment, but I think the conversion process would be similar. You can refer to this repository to convert it yourself, and then use this code for inference.

**Comment by SeanLiu081** [comment]
![image](https://github.com/bychen7/Face-Restoration-TensorRT/assets/26735847/af63fa95-6864-429b-aa34-1448f61bfe45)
I saw the issue you mentioned in the comment, and now my Python version of GPEN 512 has also encountered a significant difference in the results from onnx to trt fp16. Therefore, I am concerned about the result of converting gfpgan to trt fp16

**Comment by SeanLiu081** [comment]
why your 256 gpen speed is slower than my python trt，one img cost 25ms in T4 ，my python trt  cost 50ms/batch==4，fp32 you use?

**Comment by bychen7** [comment]
Yes, I use fp32 for GPEN and the results will be worse with fp16. I haven't tested GFPGAN with fp16.

**Comment by bychen7** [comment]
close for now.
