### ISSUE TITLE
Which cuda and tensorrt verison  are you using  in fact?

### ISSUE THREAD

**Issue by MonaZJU** [bychen7/Face-Restoration-TensorRT#5]
I use cuda11.2 and tensorrt7.2.3.4 . But there are some errors.  
Such as   no member named ‘buildSerializedNetwork’
convert.cpp:37:45: error: ‘class nvinfer1::IBuilder’ has no member named ‘buildSerializedNetwork’
     IHostMemory* serializedModel = builder->buildSerializedNetwork(*network, *c

**Comment by bychen7** [comment]
Sorry, this error is likely due to changes in the TensorRT API. I have tested it on CUDA-11.7 TensorRT-8.2.4.2/TensorRT-8.6.1.6. I will update the readme shortly.

**Comment by MonaZJU** [comment]
OK I use cuda11.2 and TensorRT-8.6.1.6 . It‘s okey.
