### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by rohaantahir** [bychen7/Face-Restoration-TensorRT#6]
Any plan to release windows version. kinldy please update.

**Comment by bychen7** [comment]
Hi, @rohaantahir I don't have any plans at the moment, I think the code doesn't need to be changed, just replace the relevant dependencies with the Windows version.

**Comment by rohaantahir** [comment]
Thanks @bychen7 I will try. Can you please tell me is there any improvement in iferrence time using this methodology as compared to using python based repo orignal from GFPGAN?

**Comment by bychen7** [comment]
The speed improvement mainly comes from using TensorRT for inference. It is possible to achieve a similar speed with the Python version as well. The difference in speed between Python and C++ is not significant. C++ is mainly used for easier SDK encapsulation.

**Comment by bychen7** [comment]
close for now.
