### ISSUE TITLE
Alternative Model download links

### ISSUE THREAD

**Issue by prakyath-07** [bychen7/Face-Restoration-TensorRT#7]
Hi, I'm not able to download models from Baidu (geo restricion). Could you please share the model using Google Drive?

Thank you in advance!

**Comment by bychen7** [comment]
Hi,@prakyath-07 Sorry for the late response. You can download the file from the following link [Google Drive](https://drive.google.com/drive/folders/1a0kuJlkicbPILrfZRM1OghYhEX4glHzL?usp=sharing).

**Comment by prakyath-07** [comment]
Thank you!
