### ISSUE TITLE
Will you support batch operation?

### ISSUE THREAD

**Issue by Life93** [bychen7/Face-Restoration-TensorRT#8]
Thank you very much for your great work and sharing. Will there be any opportunity to support batch processing in the future to further improve the inference speed for a single image? Thanks again.

**Comment by bychen7** [comment]
Hi, @Life93 Sorry, I've been a bit busy lately, and I think this isn't complicated. You can try it yourself.

**Comment by Life93** [comment]
ok, thanks

**Comment by bychen7** [comment]
Close for now. Feel free to reopen if you have any questions.
