### ISSUE TITLE
Can we directly convert gfpgan?

### ISSUE THREAD

**Issue by einsqing** [bychen7/Face-Restoration-TensorRT#9]
Can we directly convert gfpgan?

**Comment by bychen7** [comment]
Hi, @einsqing I haven't tested GFPGAN, but I think the conversion process is similar. If TensorRT is less than 8.5, modifications need to be made to ModulatedConv2d, as described in [this](https://github.com/bychen7/Face-Restoration-TensorRT/blob/main/misc/ModulatedConv2d.py). If TensorRT is 8.5 or newer, the conversion can be done directly. Additionally, I am uncertain if the preprocessing and postprocessing steps for GFPGAN are the same as GPEN. This repository is mainly based on the reference of GPEN.

**Comment by bychen7** [comment]
Close for now. Feel free to reopen if you have any questions.
